# Generated by Django 4.1.1 on 2022-10-02 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('code', models.CharField(max_length=255, verbose_name='Code')),
                ('area_name', models.CharField(max_length=255, verbose_name='Code')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('tla', models.CharField(max_length=255, null=True, verbose_name='Tla')),
                ('short_name', models.CharField(max_length=255, null=True, verbose_name='Short name')),
                ('area_name', models.CharField(max_length=255, verbose_name='Area')),
                ('address', models.CharField(max_length=255, verbose_name='Adress')),
                ('competitions', models.ManyToManyField(to='football_data.competition')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('date_of_birth', models.DateField(max_length=255, null=True, verbose_name='Date of Birth')),
                ('nationality', models.CharField(max_length=255, null=True, verbose_name='Nationality')),
                ('position', models.CharField(max_length=255, null=True, verbose_name='Position')),
                ('role', models.CharField(choices=[('PLAYER', 'Player'), ('COACH', 'Coach')], default='PLAYER', max_length=6, verbose_name='Role')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football_data.team')),
            ],
        ),
    ]
